//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPS_TOOL_DELUXE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPS_TOOL_DELUXE.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Fehler ist aufgetretten_.
        /// </summary>
        public static string anErrorHasOccurred {
            get {
                return ResourceManager.GetString("anErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapazitätsplan.
        /// </summary>
        public static string breadcrumb_capacity_planning {
            get {
                return ResourceManager.GetString("breadcrumb_capacity_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertigungsaufträge.
        /// </summary>
        public static string breadcrumb_construction_orders {
            get {
                return ResourceManager.GetString("breadcrumb_construction_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string breadcrumb_export {
            get {
                return ResourceManager.GetString("breadcrumb_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prognose.
        /// </summary>
        public static string breadcrumb_prediction {
            get {
                return ResourceManager.GetString("breadcrumb_prediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaufteildisposition.
        /// </summary>
        public static string breadcrumb_purchase_planning {
            get {
                return ResourceManager.GetString("breadcrumb_purchase_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mengenplanung.
        /// </summary>
        public static string breadcrumb_quantitative_planning {
            get {
                return ResourceManager.GetString("breadcrumb_quantitative_planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periode importieren.
        /// </summary>
        public static string dashboard_btnImportPeriod {
            get {
                return ResourceManager.GetString("dashboard_btnImportPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Periode planen.
        /// </summary>
        public static string dashboard_btnNewPeriod {
            get {
                return ResourceManager.GetString("dashboard_btnNewPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die letzten Perioden.
        /// </summary>
        public static string dashboard_headline {
            get {
                return ResourceManager.GetString("dashboard_headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erzeugnisse.
        /// </summary>
        public static string dashboard_masterdata_btn_produceItems {
            get {
                return ResourceManager.GetString("dashboard_masterdata_btn_produceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaufteile.
        /// </summary>
        public static string dashboard_masterdata_btn_purchaseItems {
            get {
                return ResourceManager.GetString("dashboard_masterdata_btn_purchaseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitsplätze.
        /// </summary>
        public static string dashboard_masterdata_btn_workplaces {
            get {
                return ResourceManager.GetString("dashboard_masterdata_btn_workplaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stammdatenverwaltung.
        /// </summary>
        public static string dashboard_masterdata_headline {
            get {
                return ResourceManager.GetString("dashboard_masterdata_headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolgreich.
        /// </summary>
        public static string dashboard_success {
            get {
                return ResourceManager.GetString("dashboard_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periode wurde erfolgreich importiert_.
        /// </summary>
        public static string dashboard_success_import {
            get {
                return ResourceManager.GetString("dashboard_success_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effizenz.
        /// </summary>
        public static string dashboard_tcEfficiency {
            get {
                return ResourceManager.GetString("dashboard_tcEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periode.
        /// </summary>
        public static string dashboard_tcPeriod {
            get {
                return ResourceManager.GetString("dashboard_tcPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewinn.
        /// </summary>
        public static string dashboard_tcProfit {
            get {
                return ResourceManager.GetString("dashboard_tcProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auslastung.
        /// </summary>
        public static string dashboard_tcWorkload {
            get {
                return ResourceManager.GetString("dashboard_tcWorkload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Perioden importiert.
        /// </summary>
        public static string dashboard_tvNoPeriodsImported {
            get {
                return ResourceManager.GetString("dashboard_tvNoPeriodsImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Periode mit der gleichen ID existiert bereits_.
        /// </summary>
        public static string error_dashboard_import_alreadyExists {
            get {
                return ResourceManager.GetString("error_dashboard_import_alreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei wurde fehlerhaft kopiert_.
        /// </summary>
        public static string error_dashboard_import_copy {
            get {
                return ResourceManager.GetString("error_dashboard_import_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die zu importierende Datei ist nicht valide_.
        /// </summary>
        public static string error_dashboard_import_JAXBException {
            get {
                return ResourceManager.GetString("error_dashboard_import_JAXBException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden mind_ zwei Perioden mit der gleichen Nummer gefunden_ Bitte korrigieren Sie die XML_Dateien in dem &apos;periods_results&apos; Verzeichnis_.
        /// </summary>
        public static string error_dashboard_periodResults_equalPeriodNumber {
            get {
                return ResourceManager.GetString("error_dashboard_periodResults_equalPeriodNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Periode wurde gelöscht, während darauf zugegriffen werden sollte_ Bitte kontaktieren Sie Ihren Administrator_.
        /// </summary>
        public static string error_dashboard_periodResults_fileDeleted {
            get {
                return ResourceManager.GetString("error_dashboard_periodResults_fileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gab ein Problem_ Bitte informieren Sie Ihren Administrator_.
        /// </summary>
        public static string error_dashboard_periodResults_folderPermissions {
            get {
                return ResourceManager.GetString("error_dashboard_periodResults_folderPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Laden der Perioden_Daten ist ein Fehler aufgetretten_ Bitte informieren Sie Ihren Administrator_.
        /// </summary>
        public static string error_dashboard_periodResults_JAXBException {
            get {
                return ResourceManager.GetString("error_dashboard_periodResults_JAXBException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Laden der Erzeugnisse ist ein Fehler aufgetretten_ Bitte informieren Sie Ihren Administrator_.
        /// </summary>
        public static string error_masterdata_produceItems_filenotfound {
            get {
                return ResourceManager.GetString("error_masterdata_produceItems_filenotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Laden der Erzeugnisse ist ein Fehler aufgetretten_ Bitte informieren Sie Ihren Administrator_.
        /// </summary>
        public static string error_masterdata_produceItems_jaxb {
            get {
                return ResourceManager.GetString("error_masterdata_produceItems_jaxb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die XML_Datei der Erzeugnisse ist nicht valide. Bitte informieren Sie Ihren Administrator..
        /// </summary>
        public static string error_masterdata_produceItems_sax {
            get {
                return ResourceManager.GetString("error_masterdata_produceItems_sax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Laden der Kaufteile ist ein Fehler aufgetretten_ Bitte informieren Sie Ihren Administrator_.
        /// </summary>
        public static string error_masterdata_purchaseItems_filenotfound {
            get {
                return ResourceManager.GetString("error_masterdata_purchaseItems_filenotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Laden der Kaufteile ist ein Fehler aufgetretten_ Bitte informieren Sie Ihren Administrator_.
        /// </summary>
        public static string error_masterdata_purchaseItems_jaxb {
            get {
                return ResourceManager.GetString("error_masterdata_purchaseItems_jaxb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die XML_Datei der Kaufteile ist nicht valide_ Bitte informieren Sie Ihren Administrator_.
        /// </summary>
        public static string error_masterdata_purchaseItems_sax {
            get {
                return ResourceManager.GetString("error_masterdata_purchaseItems_sax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Laden der Arbeitsplätze ist ein Fehler aufgetretten_ Bitte informieren Sie Ihren Administrator_.
        /// </summary>
        public static string error_masterdata_workplaces_filenotfound {
            get {
                return ResourceManager.GetString("error_masterdata_workplaces_filenotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Laden der Arbeitsplätze ist ein Fehler aufgetretten_ Bitte informieren Sie Ihren Administrator_.
        /// </summary>
        public static string error_masterdata_workplaces_jaxb {
            get {
                return ResourceManager.GetString("error_masterdata_workplaces_jaxb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die XML_Datei der Arbeitsplätze ist nicht valide_ Bitte informieren Sie Ihren Administrator_.
        /// </summary>
        public static string error_masterdata_workplaces_sax {
            get {
                return ResourceManager.GetString("error_masterdata_workplaces_sax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Eingabe ist unvollständig_ Bitte füllen Sie die entsprechend zugehörigen Werte_.
        /// </summary>
        public static string error_step_three_invalidInput {
            get {
                return ResourceManager.GetString("error_step_three_invalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Laden der nächsten Ansicht ist ein Fehler aufgetreten_ Bitte informieren Sie Ihren Administrator_.
        /// </summary>
        public static string error_view_IOException {
            get {
                return ResourceManager.GetString("error_view_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden einer Übersetzung_.
        /// </summary>
        public static string error_view_noTranslation {
            get {
                return ResourceManager.GetString("error_view_noTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Pflichtfelder.
        /// </summary>
        public static string mandatoryFields {
            get {
                return ResourceManager.GetString("mandatoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        public static string produceItems_dialog_confirm {
            get {
                return ResourceManager.GetString("produceItems_dialog_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subkomponente hinzufügen.
        /// </summary>
        public static string produceItems_dialog_subComponent {
            get {
                return ResourceManager.GetString("produceItems_dialog_subComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitsplatz hinzufügen.
        /// </summary>
        public static string produceItems_dialog_workplace {
            get {
                return ResourceManager.GetString("produceItems_dialog_workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsche Bezeichnung*.
        /// </summary>
        public static string produceItems_edit_label_de {
            get {
                return ResourceManager.GetString("produceItems_edit_label_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englische Bezeichnung*.
        /// </summary>
        public static string produceItems_edit_label_en {
            get {
                return ResourceManager.GetString("produceItems_edit_label_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanische Bezeichnung*.
        /// </summary>
        public static string produceItems_edit_label_es {
            get {
                return ResourceManager.GetString("produceItems_edit_label_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Französische Bezeichnung*.
        /// </summary>
        public static string produceItems_edit_label_fr {
            get {
                return ResourceManager.GetString("produceItems_edit_label_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rüstzeit.
        /// </summary>
        public static string produceItems_edit_setUpTime {
            get {
                return ResourceManager.GetString("produceItems_edit_setUpTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfangsbestand*.
        /// </summary>
        public static string produceItems_edit_startAmount {
            get {
                return ResourceManager.GetString("produceItems_edit_startAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subkomponente.
        /// </summary>
        public static string produceItems_edit_subComponent {
            get {
                return ResourceManager.GetString("produceItems_edit_subComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subkomponenten*.
        /// </summary>
        public static string produceItems_edit_subComponents {
            get {
                return ResourceManager.GetString("produceItems_edit_subComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        public static string produceItems_edit_subComponents_need {
            get {
                return ResourceManager.GetString("produceItems_edit_subComponents_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string produceItems_edit_subComponents_type {
            get {
                return ResourceManager.GetString("produceItems_edit_subComponents_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertigungszeit.
        /// </summary>
        public static string produceItems_edit_time {
            get {
                return ResourceManager.GetString("produceItems_edit_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benötigte Zeit.
        /// </summary>
        public static string produceItems_edit_timePerWorkplace {
            get {
                return ResourceManager.GetString("produceItems_edit_timePerWorkplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wert*.
        /// </summary>
        public static string produceItems_edit_value {
            get {
                return ResourceManager.GetString("produceItems_edit_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitsplatz.
        /// </summary>
        public static string produceItems_edit_workplace {
            get {
                return ResourceManager.GetString("produceItems_edit_workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchlaufende Arbeitsplätze*.
        /// </summary>
        public static string produceItems_edit_workplaces {
            get {
                return ResourceManager.GetString("produceItems_edit_workplaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erzeugnis bearbeiten.
        /// </summary>
        public static string produceItems_editProduceItems {
            get {
                return ResourceManager.GetString("produceItems_editProduceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erzeugnisverwaltung.
        /// </summary>
        public static string produceItems_headline {
            get {
                return ResourceManager.GetString("produceItems_headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr_.
        /// </summary>
        public static string produceItems_id {
            get {
                return ResourceManager.GetString("produceItems_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezeichnung.
        /// </summary>
        public static string produceItems_list_label {
            get {
                return ResourceManager.GetString("produceItems_list_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfangs_
        ///bestand.
        /// </summary>
        public static string produceItems_list_startAmount {
            get {
                return ResourceManager.GetString("produceItems_list_startAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subkomponenten.
        /// </summary>
        public static string produceItems_list_subComponents {
            get {
                return ResourceManager.GetString("produceItems_list_subComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wert.
        /// </summary>
        public static string produceItems_list_value {
            get {
                return ResourceManager.GetString("produceItems_list_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchlaufende
        ///Arbeitsplätze.
        /// </summary>
        public static string produceItems_list_workplaces {
            get {
                return ResourceManager.GetString("produceItems_list_workplaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferzeit Abweichung*.
        /// </summary>
        public static string purchaseItems_edit_deliverTimeVariance {
            get {
                return ResourceManager.GetString("purchaseItems_edit_deliverTimeVariance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferzeit*.
        /// </summary>
        public static string purchaseItems_edit_deliveryTime {
            get {
                return ResourceManager.GetString("purchaseItems_edit_deliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Menge*.
        /// </summary>
        public static string purchaseItems_edit_discountAmount {
            get {
                return ResourceManager.GetString("purchaseItems_edit_discountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsche Bezeichnung*.
        /// </summary>
        public static string purchaseItems_edit_label_de {
            get {
                return ResourceManager.GetString("purchaseItems_edit_label_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englische Bezeichnung*.
        /// </summary>
        public static string purchaseItems_edit_label_en {
            get {
                return ResourceManager.GetString("purchaseItems_edit_label_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanische Bezeichnung*.
        /// </summary>
        public static string purchaseItems_edit_label_es {
            get {
                return ResourceManager.GetString("purchaseItems_edit_label_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Französische Bezeichnung*.
        /// </summary>
        public static string purchaseItems_edit_label_fr {
            get {
                return ResourceManager.GetString("purchaseItems_edit_label_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellkosten*.
        /// </summary>
        public static string purchaseItems_edit_orderCosts {
            get {
                return ResourceManager.GetString("purchaseItems_edit_orderCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis*.
        /// </summary>
        public static string purchaseItems_edit_price {
            get {
                return ResourceManager.GetString("purchaseItems_edit_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfangsbestand*.
        /// </summary>
        public static string purchaseItems_edit_startAmount {
            get {
                return ResourceManager.GetString("purchaseItems_edit_startAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaufteil bearbeiten.
        /// </summary>
        public static string purchaseItems_editPurchaseItems {
            get {
                return ResourceManager.GetString("purchaseItems_editPurchaseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaufteilverwaltung.
        /// </summary>
        public static string purchaseItems_headline {
            get {
                return ResourceManager.GetString("purchaseItems_headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr_.
        /// </summary>
        public static string purchaseItems_id {
            get {
                return ResourceManager.GetString("purchaseItems_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferzeit
        ///Abweichung.
        /// </summary>
        public static string purchaseItems_list_deliverTimeVariance {
            get {
                return ResourceManager.GetString("purchaseItems_list_deliverTimeVariance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferzeit.
        /// </summary>
        public static string purchaseItems_list_deliveryTime {
            get {
                return ResourceManager.GetString("purchaseItems_list_deliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount
        ///Menge.
        /// </summary>
        public static string purchaseItems_list_discountAmount {
            get {
                return ResourceManager.GetString("purchaseItems_list_discountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezeichnung.
        /// </summary>
        public static string purchaseItems_list_label {
            get {
                return ResourceManager.GetString("purchaseItems_list_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestell_
        ///kosten.
        /// </summary>
        public static string purchaseItems_list_orderCosts {
            get {
                return ResourceManager.GetString("purchaseItems_list_orderCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis.
        /// </summary>
        public static string purchaseItems_list_price {
            get {
                return ResourceManager.GetString("purchaseItems_list_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfangs_
        ///bestand.
        /// </summary>
        public static string purchaseItems_list_startAmount {
            get {
                return ResourceManager.GetString("purchaseItems_list_startAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück zum Dashboard.
        /// </summary>
        public static string sixth_step_backToDashboard {
            get {
                return ResourceManager.GetString("sixth_step_backToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input.
        /// </summary>
        public static string sixth_step_fileName {
            get {
                return ResourceManager.GetString("sixth_step_fileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direktverkauf.
        /// </summary>
        public static string step_first_directSell {
            get {
                return ResourceManager.GetString("step_first_directSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strafe.
        /// </summary>
        public static string step_first_labPenalty {
            get {
                return ResourceManager.GetString("step_first_labPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorhersage 1.
        /// </summary>
        public static string step_first_labPrediction1 {
            get {
                return ResourceManager.GetString("step_first_labPrediction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorhersage 2.
        /// </summary>
        public static string step_first_labPrediction2 {
            get {
                return ResourceManager.GetString("step_first_labPrediction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorhersage 3.
        /// </summary>
        public static string step_first_labPrediction3 {
            get {
                return ResourceManager.GetString("step_first_labPrediction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis.
        /// </summary>
        public static string step_first_labPrice {
            get {
                return ResourceManager.GetString("step_first_labPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menge.
        /// </summary>
        public static string step_first_labQuantity {
            get {
                return ResourceManager.GetString("step_first_labQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkaufswunsch.
        /// </summary>
        public static string step_first_labSellWish {
            get {
                return ResourceManager.GetString("step_first_labSellWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkaufswunsch und Vorhersage.
        /// </summary>
        public static string step_first_labSellWishAndPrediction {
            get {
                return ResourceManager.GetString("step_first_labSellWishAndPrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte füllen Sie alle Felder aus_.
        /// </summary>
        public static string step_first_validation_emptyFields {
            get {
                return ResourceManager.GetString("step_first_validation_emptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezeichnnung.
        /// </summary>
        public static string step_five_label {
            get {
                return ResourceManager.GetString("step_five_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapa
        ///Vorp_.
        /// </summary>
        public static string step_five_neededCapacityLastPeriod {
            get {
                return ResourceManager.GetString("step_five_neededCapacityLastPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapa
        ///Neu.
        /// </summary>
        public static string step_five_neededCapacityNew {
            get {
                return ResourceManager.GetString("step_five_neededCapacityNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überstunden
        ///(Minuten/Tag).
        /// </summary>
        public static string step_five_overtime {
            get {
                return ResourceManager.GetString("step_five_overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rüstzeit
        ///Vorp_.
        /// </summary>
        public static string step_five_setUpTimeLastPeriod {
            get {
                return ResourceManager.GetString("step_five_setUpTimeLastPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rüstzeit
        ///Neu.
        /// </summary>
        public static string step_five_setUpTimeNew {
            get {
                return ResourceManager.GetString("step_five_setUpTimeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schichten.
        /// </summary>
        public static string step_five_shifts {
            get {
                return ResourceManager.GetString("step_five_shifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt_
        ///bedarf.
        /// </summary>
        public static string step_five_total {
            get {
                return ResourceManager.GetString("step_five_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr_.
        /// </summary>
        public static string step_five_workplace {
            get {
                return ResourceManager.GetString("step_five_workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        public static string step_four_count {
            get {
                return ResourceManager.GetString("step_four_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr_.
        /// </summary>
        public static string step_four_id {
            get {
                return ResourceManager.GetString("step_four_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl 
        ///Fertigungs_
        ///aufträge.
        /// </summary>
        public static string step_second_amountOfProductionOrders {
            get {
                return ResourceManager.GetString("step_second_amountOfProductionOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr_.
        /// </summary>
        public static string step_second_itemNumber {
            get {
                return ResourceManager.GetString("step_second_itemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufträge 
        ///Bearbeitung.
        /// </summary>
        public static string step_second_ordersInProcess {
            get {
                return ResourceManager.GetString("step_second_ordersInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufträge 
        ///Warteliste.
        /// </summary>
        public static string step_second_ordersInWaitinglist {
            get {
                return ResourceManager.GetString("step_second_ordersInWaitinglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planbestand.
        /// </summary>
        public static string step_second_plannedAmount {
            get {
                return ResourceManager.GetString("step_second_plannedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicherheits_
        ///bestand.
        /// </summary>
        public static string step_second_saveStock {
            get {
                return ResourceManager.GetString("step_second_saveStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestand 
        ///Vorperiode.
        /// </summary>
        public static string step_second_stockFromPeriodBefore {
            get {
                return ResourceManager.GetString("step_second_stockFromPeriodBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eil.
        /// </summary>
        public static string step_third_combobox_express {
            get {
                return ResourceManager.GetString("step_third_combobox_express", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string step_third_combobox_normal {
            get {
                return ResourceManager.GetString("step_third_combobox_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbrauch.
        /// </summary>
        public static string step_third_consumption {
            get {
                return ResourceManager.GetString("step_third_consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktueller
        ///Bestand.
        /// </summary>
        public static string step_third_currentAmount {
            get {
                return ResourceManager.GetString("step_third_currentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liefer_
        ///dauer
        ///Eil.
        /// </summary>
        public static string step_third_hurryUpArrivalDate {
            get {
                return ResourceManager.GetString("step_third_hurryUpArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr_.
        /// </summary>
        public static string step_third_itemNumber {
            get {
                return ResourceManager.GetString("step_third_itemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Längste
        ///Liefer_
        ///dauer.
        /// </summary>
        public static string step_third_latestArrivalDate {
            get {
                return ResourceManager.GetString("step_third_latestArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normale
        ///Liefer_
        ///dauer.
        /// </summary>
        public static string step_third_normalArrivalDate {
            get {
                return ResourceManager.GetString("step_third_normalArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offene
        ///Bestellungen.
        /// </summary>
        public static string step_third_openOrders {
            get {
                return ResourceManager.GetString("step_third_openOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestell_
        ///menge.
        /// </summary>
        public static string step_third_orderQuantity {
            get {
                return ResourceManager.GetString("step_third_orderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diskont_
        ///menge.
        /// </summary>
        public static string step_third_quantity {
            get {
                return ResourceManager.GetString("step_third_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellart.
        /// </summary>
        public static string step_third_typeOfOrder {
            get {
                return ResourceManager.GetString("step_third_typeOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erzeugnis wurde erfolgreich gespeichert_.
        /// </summary>
        public static string success_masterdata_produceItems_saved {
            get {
                return ResourceManager.GetString("success_masterdata_produceItems_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaufteil wurde erfolgreich gespeichert_.
        /// </summary>
        public static string success_masterdata_purchaseItems_saved {
            get {
                return ResourceManager.GetString("success_masterdata_purchaseItems_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitsplatz wurde erfolgreich gespeichert_.
        /// </summary>
        public static string success_masterdata_workplaces_saved {
            get {
                return ResourceManager.GetString("success_masterdata_workplaces_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gespeichert!.
        /// </summary>
        public static string success_saved {
            get {
                return ResourceManager.GetString("success_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte füllen Sie jedes mit einem * markiertes Feld aus_.
        /// </summary>
        public static string validation_emptyFields {
            get {
                return ResourceManager.GetString("validation_emptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überstunden* (€/Min).
        /// </summary>
        public static string workplaces_edit_extraHour {
            get {
                return ResourceManager.GetString("workplaces_edit_extraHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1_ Schicht* (€/Min).
        /// </summary>
        public static string workplaces_edit_firstStint {
            get {
                return ResourceManager.GetString("workplaces_edit_firstStint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsche Bezeichnung*.
        /// </summary>
        public static string workplaces_edit_label_de {
            get {
                return ResourceManager.GetString("workplaces_edit_label_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englische Bezeichnung*.
        /// </summary>
        public static string workplaces_edit_label_en {
            get {
                return ResourceManager.GetString("workplaces_edit_label_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanische Bezeichnung*.
        /// </summary>
        public static string workplaces_edit_label_es {
            get {
                return ResourceManager.GetString("workplaces_edit_label_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Französische Bezeichnung*.
        /// </summary>
        public static string workplaces_edit_label_fr {
            get {
                return ResourceManager.GetString("workplaces_edit_label_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maschinenkosten fix*.
        /// </summary>
        public static string workplaces_edit_machineCosts_fix {
            get {
                return ResourceManager.GetString("workplaces_edit_machineCosts_fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maschinenkosten var*.
        /// </summary>
        public static string workplaces_edit_machineCosts_var {
            get {
                return ResourceManager.GetString("workplaces_edit_machineCosts_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2_ Schicht* (€/Min).
        /// </summary>
        public static string workplaces_edit_secondStint {
            get {
                return ResourceManager.GetString("workplaces_edit_secondStint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3_ Schicht* (€/Min).
        /// </summary>
        public static string workplaces_edit_thirdStint {
            get {
                return ResourceManager.GetString("workplaces_edit_thirdStint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitsplatz bearbeiten.
        /// </summary>
        public static string workplaces_editWorkplace {
            get {
                return ResourceManager.GetString("workplaces_editWorkplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitsplatzverwaltung.
        /// </summary>
        public static string workplaces_headline {
            get {
                return ResourceManager.GetString("workplaces_headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr_.
        /// </summary>
        public static string workplaces_id {
            get {
                return ResourceManager.GetString("workplaces_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überstunden
        ///€/Min.
        /// </summary>
        public static string workplaces_list_extraHour {
            get {
                return ResourceManager.GetString("workplaces_list_extraHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1_ Schicht
        ///€/Min.
        /// </summary>
        public static string workplaces_list_firstStint {
            get {
                return ResourceManager.GetString("workplaces_list_firstStint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezeichnung.
        /// </summary>
        public static string workplaces_list_label {
            get {
                return ResourceManager.GetString("workplaces_list_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maschinenkosten
        ///fix.
        /// </summary>
        public static string workplaces_list_machineCosts_fix {
            get {
                return ResourceManager.GetString("workplaces_list_machineCosts_fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maschinenkosten
        ///var.
        /// </summary>
        public static string workplaces_list_machineCosts_var {
            get {
                return ResourceManager.GetString("workplaces_list_machineCosts_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2_ Schicht
        ///€/Min.
        /// </summary>
        public static string workplaces_list_secondStint {
            get {
                return ResourceManager.GetString("workplaces_list_secondStint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3_ Schicht
        ///€/Min.
        /// </summary>
        public static string workplaces_list_thirdStint {
            get {
                return ResourceManager.GetString("workplaces_list_thirdStint", resourceCulture);
            }
        }
    }
}
