//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class purchaseItems {
    
    private purchaseItemsItem[] itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item")]
    public purchaseItemsItem[] item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaseItemsItem {
    
    private int idField;
    
    private purchaseItemsItemLabel labelField;
    
    private object stockValueField;
    
    private int startAmountField;
    
    private int discountAmountField;
    
    private double deliveryTimeField;
    
    private double deliveryTimeVarianceField;
    
    private double orderCostsField;
    
    private double priceField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public purchaseItemsItemLabel label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    public object stockValue {
        get {
            return this.stockValueField;
        }
        set {
            this.stockValueField = value;
        }
    }
    
    /// <remarks/>
    public int startAmount {
        get {
            return this.startAmountField;
        }
        set {
            this.startAmountField = value;
        }
    }
    
    /// <remarks/>
    public int discountAmount {
        get {
            return this.discountAmountField;
        }
        set {
            this.discountAmountField = value;
        }
    }
    
    /// <remarks/>
    public double deliveryTime {
        get {
            return this.deliveryTimeField;
        }
        set {
            this.deliveryTimeField = value;
        }
    }
    
    /// <remarks/>
    public double deliveryTimeVariance {
        get {
            return this.deliveryTimeVarianceField;
        }
        set {
            this.deliveryTimeVarianceField = value;
        }
    }
    
    /// <remarks/>
    public double orderCosts {
        get {
            return this.orderCostsField;
        }
        set {
            this.orderCostsField = value;
        }
    }
    
    /// <remarks/>
    public double price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaseItemsItemLabel {
    
    private string deField;
    
    private string enField;
    
    private string esField;
    
    private string frField;
    
    /// <remarks/>
    public string de {
        get {
            return this.deField;
        }
        set {
            this.deField = value;
        }
    }
    
    /// <remarks/>
    public string en {
        get {
            return this.enField;
        }
        set {
            this.enField = value;
        }
    }
    
    /// <remarks/>
    public string es {
        get {
            return this.esField;
        }
        set {
            this.esField = value;
        }
    }
    
    /// <remarks/>
    public string fr {
        get {
            return this.frField;
        }
        set {
            this.frField = value;
        }
    }
}
