//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class workspaces {
    
    private workspacesWorkspace[] workspaceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("workspace")]
    public workspacesWorkspace[] workspace {
        get {
            return this.workspaceField;
        }
        set {
            this.workspaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class workspacesWorkspace {
    
    private workspacesWorkspaceLabel labelField;
    
    private workspacesWorkspaceCosts costsField;
    
    private int idField;
    
    private bool idFieldSpecified;
    
    /// <remarks/>
    public workspacesWorkspaceLabel label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    public workspacesWorkspaceCosts costs {
        get {
            return this.costsField;
        }
        set {
            this.costsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class workspacesWorkspaceLabel {
    
    private string deField;
    
    private string enField;
    
    private string esField;
    
    private string frField;
    
    /// <remarks/>
    public string de {
        get {
            return this.deField;
        }
        set {
            this.deField = value;
        }
    }
    
    /// <remarks/>
    public string en {
        get {
            return this.enField;
        }
        set {
            this.enField = value;
        }
    }
    
    /// <remarks/>
    public string es {
        get {
            return this.esField;
        }
        set {
            this.esField = value;
        }
    }
    
    /// <remarks/>
    public string fr {
        get {
            return this.frField;
        }
        set {
            this.frField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class workspacesWorkspaceCosts {
    
    private double firstStintField;
    
    private double secondStintField;
    
    private double thirdStintField;
    
    private double extraHourField;
    
    private workspacesWorkspaceCostsMaschine maschineField;
    
    /// <remarks/>
    public double firstStint {
        get {
            return this.firstStintField;
        }
        set {
            this.firstStintField = value;
        }
    }
    
    /// <remarks/>
    public double secondStint {
        get {
            return this.secondStintField;
        }
        set {
            this.secondStintField = value;
        }
    }
    
    /// <remarks/>
    public double thirdStint {
        get {
            return this.thirdStintField;
        }
        set {
            this.thirdStintField = value;
        }
    }
    
    /// <remarks/>
    public double extraHour {
        get {
            return this.extraHourField;
        }
        set {
            this.extraHourField = value;
        }
    }
    
    /// <remarks/>
    public workspacesWorkspaceCostsMaschine maschine {
        get {
            return this.maschineField;
        }
        set {
            this.maschineField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class workspacesWorkspaceCostsMaschine {
    
    private double variableField;
    
    private double fixField;
    
    /// <remarks/>
    public double variable {
        get {
            return this.variableField;
        }
        set {
            this.variableField = value;
        }
    }
    
    /// <remarks/>
    public double fix {
        get {
            return this.fixField;
        }
        set {
            this.fixField = value;
        }
    }
}
