//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class produceItems {
    
    private produceItemsItem[] itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item")]
    public produceItemsItem[] item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class produceItemsItem {
    
    private int idField;
    
    private produceItemsItemLabel labelField;
    
    private int startAmountField;
    
    private produceItemsItemSubComponent[] subComponentListField;
    
    private double valueField;
    
    private produceItemsItemWorkplace[] timePerWorkplaceField;

    public string WorkplacesToString()
    {
        var result = "";
        foreach (var workplace in timePerWorkplaceField)
            result += $"{workplace.id};";
        return result;
    }

    public string SubComponentsToString()
    {
        var result = "";
        foreach (var component in subComponentListField)
            result += $"{component.id};";
        return result;
    }

    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public produceItemsItemLabel label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    public int startAmount {
        get {
            return this.startAmountField;
        }
        set {
            this.startAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("subComponent", IsNullable=false)]
    public produceItemsItemSubComponent[] subComponentList {
        get {
            return this.subComponentListField;
        }
        set {
            this.subComponentListField = value;
        }
    }
    
    /// <remarks/>
    public double value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("workplace", IsNullable=false)]
    public produceItemsItemWorkplace[] timePerWorkplace {
        get {
            return this.timePerWorkplaceField;
        }
        set {
            this.timePerWorkplaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class produceItemsItemLabel {
    
    private string deField;
    
    private string enField;
    
    private string esField;
    
    private string frField;
    
    /// <remarks/>
    public string de {
        get {
            return this.deField;
        }
        set {
            this.deField = value;
        }
    }
    
    /// <remarks/>
    public string en {
        get {
            return this.enField;
        }
        set {
            this.enField = value;
        }
    }
    
    /// <remarks/>
    public string es {
        get {
            return this.esField;
        }
        set {
            this.esField = value;
        }
    }
    
    /// <remarks/>
    public string fr {
        get {
            return this.frField;
        }
        set {
            this.frField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class produceItemsItemSubComponent {
    
    private int idField;
    
    private string typField;
    
    private int needField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string typ {
        get {
            return this.typField;
        }
        set {
            this.typField = value;
        }
    }
    
    /// <remarks/>
    public int need {
        get {
            return this.needField;
        }
        set {
            this.needField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class produceItemsItemWorkplace {
    
    private int idField;
    
    private int timeField;
    
    private int setUpTimeField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public int time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    public int setUpTime {
        get {
            return this.setUpTimeField;
        }
        set {
            this.setUpTimeField = value;
        }
    }
}
